### ISSUE TITLE
Email and S3 configuration

### ISSUE THREAD

**Issue by LeaderBoy** [mkizka/mastodon-railway-template#1]
I like this template, thank you for creating it, but I don't know how to configure SMTP and S3 storage services. Can you please tell me how to do it?

**Comment by mkizka** [comment]
Thank you. There are no specific settings for this template about SMTP and S3. Simply add the environment variables according to the official Mastodon documentation and redeploy.

The documentation is likely this.
https://docs.joinmastodon.org/admin/config/#smtp
https://docs.joinmastodon.org/admin/optional/object-storage/
